#!/bin/bash
# Use t2.micro. If you use t3.micro then the network interface should be ens5 in the playbook.

# GIVE ONLY BELOW IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING
sudo apt update
sudo apt install software-properties-common -y
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt update
sudo apt install ansible -y
sudo apt install nginx -y
sudo apt install python-apt -y
sudo apt install -y git stress
sudo git clone -b aws_autoscaling_test https://github.com/github-mbm/aws-autoscaling.git /myrepo

# GIVE BELOW IN THE LAUNCH CONFIG USERDATA
ansible-playbook /myrepo/playbook.yaml
